### PR TITLE
Fix for `objectKeyRx` and `directiveRx`

### PR DESCRIPTION
**Pull request by qkeitoe**
I think I've managed to find (and fix) the cause of the issue https://github.com/rbjaxter/budhud/issues/536.

But since I have no idea how to compile this project, I haven't been able to test the fix yet.

### CODE REVIEW

**Comment by qkeitoe** [comment]
Also, I believe the issue https://github.com/rbjaxter/budhud/issues/498 is caused by one (or both) of these regex expressions:
https://github.com/rbjaxter/budhud-compiler/blob/0c1d4a43d79b852716c2fce295c64c7ed550acc3/Program.cs#L126
https://github.com/rbjaxter/budhud-compiler/blob/0c1d4a43d79b852716c2fce295c64c7ed550acc3/Program.cs#L219
This can also potentially be fixed, but I'd like to make sure the original fix works first.

**Comment by qkeitoe** [comment]
@rbjaxter Will you have an opportunity to test this fix?

**Comment by rbjaxter** [comment]
Thanks for bumping this, I don't know if I was notified of the PR. I'll give it a shot compiling

**Comment by rbjaxter** [comment]
I compiled the project and it seems to have resolved the issue as far as I can tell, though admittedly I just checked the quit menu compiled vs uncompiled because I honestly don't know what else to check since I basically can never use compiled budhud 😔. If you wanted to test it on your end, here's a link to the version I compiled: https://www.dropbox.com/s/vfttlc29ixluxfv/budhud-compiler.exe?dl=0

..it feels wrong to send someone an .exe lmao

**Comment by rbjaxter** [comment]
Alternatively, compiling isn't actually too bad-- you just need to `git bash` into the csproject's location and then run:
`dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true`

Then this generates a file here:
`budhud-compiler\bin\Release\netX.X\win-x64\publish`

This may not be the appropriate way to go about it, but it's all I really know how to do lmao

**Comment by qkeitoe** [comment]
@rbjaxter Here is the difference in compiled files (with tests for proper handling of quotes around `#base` keywords): [diff.zip](https://github.com/user-attachments/files/17398348/diff.zip) (generated via WinMerge). Looks good for me.

**Comment by rbjaxter** [comment]
Seems good to me, thank you for looking into this!

**Pull request merged**
